import React, { useState } from 'react';
import { Download, FileText, FileCode, Check, Copy, Share2, X } from 'lucide-react';
import { ResearchRun } from '../../types';

interface ExportModalProps {
  run: ResearchRun | null;
  isOpen: boolean;
  onClose: () => void;
}

export const ExportModal: React.FC<ExportModalProps> = ({ run, isOpen, onClose }) => {
  const [copiedFormat, setCopiedFormat] = useState<string | null>(null);

  if (!isOpen || !run) return null;

  const handleExport = (format: 'markdown' | 'pdf' | 'docx') => {
    if (format === 'markdown') {
      const mdContent = `# ${run.topic}

**Generated by ResearchFlow Autonomous Multi-Agent Swarm**
**Date:** ${run.createdAt} | **Depth:** ${run.depth.toUpperCase()} | **Audience:** ${run.audience}

---

${run.reportSections
  .map(
    s => `## ${s.orderNumber} — ${s.title}
Confidence: ${s.confidence} (${s.verifiedClaims} claims verified)

${s.paragraphs.join('\n\n')}
`
  )
  .join('\n---\n')}

## Sources
${run.sources
  .map(
    src =>
      `[${src.id}] ${src.name} (${src.publishedYear || '2026'}). "${src.title}". ${src.url}`
  )
  .join('\n')}
`;

      const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8;' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${run.topic.slice(0, 30).replace(/\s+/g, '-').toLowerCase()}-report.md`;
      link.click();
    }

    setCopiedFormat(format);
    setTimeout(() => {
      setCopiedFormat(null);
      onClose();
    }, 1500);
  };

  return (
    <div className="fixed inset-0 bg-black/40 backdrop-blur-xs flex items-center justify-center p-3 sm:p-4 z-50 animate-in fade-in duration-150">
      <div className="bg-white rounded-2xl border border-[#D5D9DC] shadow-2xl max-w-md w-full p-4 sm:p-6 text-left space-y-4 sm:space-y-5 max-h-[90vh] overflow-y-auto">
        <div className="flex items-center justify-between">
          <div>
            <h3 className="text-sm sm:text-base font-bold text-[#0F2027]">Export Research Report</h3>
            <p className="text-[11px] sm:text-xs text-[#7D878D] mt-0.5">
              Download complete synthesis with full citation provenance
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-lg text-[#7D878D] hover:text-[#0F2027] hover:bg-[#F2FAFF] cursor-pointer"
            aria-label="Close export dialog"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Options */}
        <div className="space-y-2 sm:space-y-2.5">
          {/* Markdown */}
          <button
            onClick={() => handleExport('markdown')}
            className="w-full flex items-center justify-between p-3 sm:p-3.5 rounded-xl border border-[#D5D9DC] hover:border-[#1B61EB] hover:bg-[#F2FAFF] transition-all text-left group cursor-pointer"
          >
            <div className="flex items-center gap-2.5 sm:gap-3 min-w-0">
              <div className="w-8 h-8 sm:w-9 sm:h-9 rounded-lg bg-[#F2FAFF] text-[#1B61EB] flex items-center justify-center group-hover:scale-105 transition-transform shrink-0">
                <FileCode className="w-4 h-4 sm:w-5 sm:h-5" />
              </div>
              <div className="min-w-0">
                <span className="font-semibold text-xs text-[#0F2027] block">Markdown (.md)</span>
                <span className="text-[10px] sm:text-[11px] text-[#53616A] line-clamp-1">
                  Clean formatted text with headers, quotes, and bib references
                </span>
              </div>
            </div>
            {copiedFormat === 'markdown' ? (
              <Check className="w-4 h-4 text-emerald-600 shrink-0 ml-2" />
            ) : (
              <Download className="w-4 h-4 text-[#7D878D] group-hover:text-[#1B61EB] shrink-0 ml-2" />
            )}
          </button>

          {/* PDF */}
          <button
            onClick={() => handleExport('pdf')}
            className="w-full flex items-center justify-between p-3 sm:p-3.5 rounded-xl border border-[#D5D9DC] hover:border-[#1B61EB] hover:bg-[#F2FAFF] transition-all text-left group cursor-pointer"
          >
            <div className="flex items-center gap-2.5 sm:gap-3 min-w-0">
              <div className="w-8 h-8 sm:w-9 sm:h-9 rounded-lg bg-rose-50 text-rose-600 flex items-center justify-center group-hover:scale-105 transition-transform shrink-0">
                <FileText className="w-4 h-4 sm:w-5 sm:h-5" />
              </div>
              <div className="min-w-0">
                <span className="font-semibold text-xs text-[#0F2027] block">PDF Document (.pdf)</span>
                <span className="text-[10px] sm:text-[11px] text-[#53616A] line-clamp-1">
                  Executive briefing layout with embedded telemetry cards
                </span>
              </div>
            </div>
            {copiedFormat === 'pdf' ? (
              <Check className="w-4 h-4 text-emerald-600 shrink-0 ml-2" />
            ) : (
              <Download className="w-4 h-4 text-[#7D878D] group-hover:text-[#1B61EB] shrink-0 ml-2" />
            )}
          </button>

          {/* Word DOCX */}
          <button
            onClick={() => handleExport('docx')}
            className="w-full flex items-center justify-between p-3 sm:p-3.5 rounded-xl border border-[#D5D9DC] hover:border-[#1B61EB] hover:bg-[#F2FAFF] transition-all text-left group cursor-pointer"
          >
            <div className="flex items-center gap-2.5 sm:gap-3 min-w-0">
              <div className="w-8 h-8 sm:w-9 sm:h-9 rounded-lg bg-[#1B61EB]/10 text-[#1B61EB] flex items-center justify-center group-hover:scale-105 transition-transform shrink-0">
                <FileText className="w-4 h-4 sm:w-5 sm:h-5" />
              </div>
              <div className="min-w-0">
                <span className="font-semibold text-xs text-[#0F2027] block">Microsoft Word (.docx)</span>
                <span className="text-[10px] sm:text-[11px] text-[#53616A] line-clamp-1">
                  Editable corporate template with table of contents
                </span>
              </div>
            </div>
            {copiedFormat === 'docx' ? (
              <Check className="w-4 h-4 text-emerald-600 shrink-0 ml-2" />
            ) : (
              <Download className="w-4 h-4 text-[#7D878D] group-hover:text-[#1B61EB] shrink-0 ml-2" />
            )}
          </button>
        </div>

        {/* Footer info note */}
        <div className="pt-2 border-t border-[#D5D9DC] flex items-center justify-between text-[11px] text-[#7D878D]">
          <span>Includes verified footnotes</span>
          <button
            onClick={onClose}
            className="text-[#1B61EB] hover:underline cursor-pointer"
          >
            Dismiss
          </button>
        </div>
      </div>
    </div>
  );
};
